server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        exclude: "*"