server:
  port: 9091

spring:
  application:
    name: payment
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  cloud:
    function:
      definition: ticketReservedHandler;bookingEventProcessor
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        ticketReservedHandler-in-0:
          destination: ticket-events-topic
          group: payment-service-group
          content-type: application/json
        ticketReservedHandler-out-0:
          destination: payment-events-topic
          group: payment-service-group
          content-type: application/json
        bookingEventProcessor-in-0:
          destination: booking-canceled-topic
          group: payment-service-group
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/