server:
  port: 9091

spring:
  application:
    name: payment-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      definition: paymentCommandProcessor
    stream:
      default-binder: rabbit
      bindings:
        paymentCommandProcessor-in-0:
          destination: payment-commands-exchange
          group: payment-service-group
          content-type: application/json
        paymentCommandProcessor-out-0:
          destination: payment-replies-exchange
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/