server:
  port: 9090

spring:
  application:
    name: booking-service
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    function:
      definition: ticketProducer;paymentProducer;ticketEventProcessor;paymentEventProcessor
    stream:
      default-binder: rabbit
      bindings:
        ticketProducer-out-0:
          destination: ticket-commands-exchange
          content-type: application/json
        paymentProducer-out-0:
          destination: payment-commands-exchange
          content-type: application/json
        ticketEventProcessor-in-0:
          destination: ticket-replies-exchange
          group: booking-saga-group
          content-type: application/json
        paymentEventProcessor-in-0:
          destination: payment-replies-exchange
          group: booking-saga-group
          content-type: application/json
          binder:

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/