server:
  port: 9090

spring:
  application:
    name: booking-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  cloud:
    function:
      definition: ticketProducer;paymentProducer;ticketEventProcessor;paymentEventProcessor
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            spring.json.trusted.packages: "*"
            spring.json.use.type.headers: false
            producer-properties:
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        ticketProducer-out-0:
          destination: ticket-commands
          content-type: application/json
        ticketEventProcessor-in-0:
          destination: ticket-commands-response
          group: booking-completed-group
          content-type: application/json
        paymentProducer-out-0:
          destination: payment-commands
          group: booking-canceled-group
          content-type: application/json
        paymentEventProcessor-in-0:
          destination: payment-commands-response
          group: booking-canceled-group
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/