server:
  port: 9093

spring:
  application:
    name: tickets
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ticket-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: bookingEventProcessor;paymentConfirmationProcessor
    stream:
      default-binder: rabbit
      bindings:
        bookingEventProcessor-in-0:
          destination: booking-events-exchange
          group: booking-ticket-service-queue
          content-type: application/json
        bookingEventProcessor-out-0:
          destination: ticket-events-exchange
          content-type: application/json
        paymentConfirmationProcessor-in-0:
          destination: payment-events-exchange
          group: payment-ticket-service-queue
          content-type: application/json
        paymentConfirmationProcessor-out-0:
          destination: payment-ticket-events-exchange
          content-type: application/json

      rabbit:
        bindings:
          bookingEventProcessor-in-0:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: 'booking.#'
          bookingEventProcessor-out-0:
            producer:
              routingKeyExpression: headers['routingKey']
          paymentConfirmationProcessor-in-0:
            consumer:
              bindingRoutingKey: 'payment.processed'
          paymentConfirmationProcessor-out-0:
            producer:
              routingKeyExpression: "'ticket.confirmed'"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/