server:
  port: 9093

spring:
  application:
    name: ticket-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ticket-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: ticketCommandProcessor
    stream:
      default-binder: rabbit
      bindings:
        ticketCommandProcessor-in-0:
          destination: ticket-commands-exchange
          group: ticket-service-group
          content-type: application/json
        ticketCommandProcessor-out-0:
          destination: ticket-replies-exchange
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/