server:
  port: 9093

spring:
  application:
    name: ticket-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ticket-service-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  cloud:
    function:
      definition: ticketCommandProcessor
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        ticketCommandProcessor-in-0:
          destination: ticket-commands
          group: booking-ticket-service-group
          content-type: application/json
        ticketCommandProcessor-out-0:
          destination: ticket-commands-response
          content-type: application/json

#logging:
#  level:
#    org.springframework.cloud.stream: DEBUG
#    org.springframework.integration: DEBUG
#
#    org.springframework.kafka: DEBUG
#
#    # Isso vai mostrar se ele está entrando no grupo (Rebalance) ou buscando dados (Fetch)
#    org.apache.kafka.clients.consumer: DEBUG
#    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG
#
#    org.springframework.kafka.support.converter: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/